environment:

  matrix:

    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python36"

install:
  - "%PYTHON%\\python.exe -m pip install pytest"

build: off

test_script:
  - "%PYTHON%\\python.exe -m pytest -v -l test_syncobj.py"
