environment:

  matrix:

    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python33"

install:
  # We need wheel installed to build wheels
  - "%PYTHON%\\python.exe -m pip install pytest"

build: off

test_script:
  # Put your test command here.
  # If you don't need to build C extensions on 64-bit Python 3.3 or 3.4,
  # you can remove "build.cmd" from the front of the command, as it's
  # only needed to support those cases.
  # Note that you must use the environment variable %PYTHON% to refer to
  # the interpreter you're using - Appveyor does not do anything special
  # to put the Python evrsion you want to use on PATH.
  - "%PYTHON%\\python.exe -m pytest -v -l test_syncobj.py"
