name: Tests

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run_tests
        run: >
          ls -la &&
          python3 -m pip install -U pytest &&
          python3 -m pytest -v -s test_syncobj.py
